server:
  port: 8081
  servlet:
    context-path: /indentity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FinTrip?useSSL=false&serverTimezone=UTC
    username: root
    password: Tuan@1312003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fintriptravel@gmail.com
    password: yist lbjc sylt qjbb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400