server:
  port: 8081
  servlet:
    context-path: /indentity
payos:
  client-id: c1d52240-f7ee-4093-acf6-df9f0a994a1f
  api-key: 384f9577-4779-467b-ac50-9b9d3d59d7c1
  checksum-key: 7d3b365070f2c6e1bcc5ff2950f6bc8457a038c74afdf205b3bd415132b54237
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FinTrip?useSSL=false&serverTimezone=UTC
    username: root
    password: Tuan@1312003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fintriptravel@gmail.com
    password: yist lbjc sylt qjbb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400