server:
  port: 8080
  servlet:
    context-path: /indentity
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FinTrip;encrypt=false
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto : update
    show-sql : true
